### ISSUE TITLE
Rename GetGLPISessionToken to Get-GLPISessionToken

### ISSUE THREAD

**Issue by rebrec** [J-C-P/PSGLPI#1]
Hi and thanks for this module.
Just to inform you that it seems there is a typo on the cmdlet GetGLPISessionToken which should be Get-GLPISessionToken

Regards

**Comment by J-C-P** [comment]
Sorry for the long delay in the answer.
This is by design.
The internal functions have names WITHOUT dash "-" character to differentiate them from the exposed functions.
